### ISSUE TITLE
Quotable base91

### ISSUE THREAD

**Issue by r-lyeh** [malamanteau/HandyCpp#1]
Hey there,
Glad that base sources found a place in this new home :D

I had a read on these lines:
https://github.com/malamanteau/HandyCpp/blob/b8789ccd3aa379b0b476a0ac2c9ec3fb5d80de97/HandyEncoding.hpp#L68

Are you using the original base91 or base91x (my mod)? ('cos base91x should be quotable, and also JSON, XML and TSV friendly unless I'm wrong).

Btw, I hereby give you explicit dual-licensing of my base sources under zlib AND Unlicense \o/ Feel free to remove all the legal stuff (related to me) that clutters your LICENSE file :D

**Comment by malamanteau** [comment]
Brilliant, thank you! 
I think I fixed the comments (I had the labels between yours and the original swapped).
